### ISSUE TITLE
Adding Contributor

### ISSUE THREAD

**Issue by JKChai** [SL96-new/Harlo-Python#1]
Contributor needed to be added to help facilitate Python & Git learning process. @SL96-new 

Useful Links to allow permissions
* [Invite Collaborators](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository)
* [Access Permissions](https://docs.github.com/en/get-started/learning-about-github/access-permissions-on-github)
* [Permission User Repositories](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-user-account-settings/permission-levels-for-a-user-account-repository)

**Comment by SL96-new** [comment]
Invitation done (Collaborator)
