### ISSUE TITLE
Understanding & Adept with Google Colab

### ISSUE THREAD

**Issue by SL96-new** [SL96-new/Harlo-Python#3]
Colab Overview

**Comment by JKChai** [comment]
Make title more readable and descriptive. Do note that the goal here is to get more comfortable to write and code in Google Colab. @SL96-new

**Comment by SL96-new** [comment]
Day 2 
- Learning Markdown basic syntax from Documentation Links
1. Markdown GitHub Using VSCode 
2. Colab Markdown Guide

may refer to sample.md 

Q1 : what do I need to check in git bash before execute the 'git pull' command the updated version from git hub everyday ?

**Comment by JKChai** [comment]
@SL96-new  Check this link https://www.atlassian.com/git/tutorials/syncing/git-pull for tutorial and understand more about `git pull` command. Essentially, operating `git pull` every time before making update to your local `main` repo will help to stay up-to-date in regard to any changes make from the remote repository by others, in this case, me. Best practice is to create a new branch such as a `progress` branch where you will have your code modified from the main/master repo. This will provide an up-to-date branch from the remote repo and simultaneously continue to work on the branch that you are working independently on without conflicting with the up-to-date local repo. A more advance technique will involve `git merge` where you will select what to combine from 2 repos and `git diff` where you will make decision about what to remove and what to add from the other repository.

**Comment by SL96-new** [comment]
Day 3
Read through Github basic formatting syntax , GitHub flavored Markdown (GFM) which similar as Markdown, however there are extra features in Github, for example issues, reference functions.

**Comment by JKChai** [comment]
@SL96-new 👍  Noted on Day 3, please continue to move on with all of the basics required for GitHub and moved into Python sooner.

**Comment by SL96-new** [comment]
#**Chapter 6**
Information / Data Type
1. Integers 整数 {5, 100, 806}
2. Floating-point 含小数点的数值 {0.1, 0.725, 3.5}
3. Boolean 布林值 {True, False}
4. Strings 文字 `any grouping of characters` {"Halo" "Python"}
5. Dates and Times
Note : ``` 9 (integers)  != 9.0 (floating point value), different type variable ```

---
#**Chapter 7 Managing Information**
Operators
1. Unary  正负数，转化二进制数据 {+ - ~}
2. Arithmetic 四则运算、余数、指数、商 {+ - * / % ** // }
3. Relational 等于、不等、大于、小于、大于等于、小于等于 {== != > < >= <=} 
4. Logical: {and or not}
5. Bitwise 于二进制层面进行转换 {&(and) |(or) ^(Exclusive or) ~ << >>} 
6. Assignment 主要赋予Variable值 {Arithmetic 搭配等号使用}
7. Membership {In Not in}
8. Identity {Is Is not}

Function
1. Define
2. Arguments (as default value, can more than 1, can be user's input) 
3. Return information `return` function运算最终的结果将返回并赋值于 variable 中

**Comment by SL96-new** [comment]
**# Chapter 8 Making Decision**
If 
1. single condition > single statement
2. single condition > multiple statements
3. multiple conditions > one or more statements

if... else :  `else` statement executes when the condition for the `if` statement aren't met.
if...elif : create another set of conditions (can use more than one time)

---
**# Chapter 9 Performing Repetitive Tasks (LOOP)**
1. For : work through a sequence
   a. break : making breaking out of a loop. 
   b. continue : continues with the next element in the sequence as skip current loop iteration.
   c. pass : bypass specific elements in sequence and allows completion of the code in the `if` statement
   d. else : executing code possible even if no elements to process on sequence.
2. While :  work through a condition
   a. Create the environment for the condition (eg: sum = 0 ) 
   b. State the condition within the while statement (eg: sum <5) 
   c. update the condition as needed to ensure that the loop eventually ends ( sum += 1 each round) 
   ( same as above `break` `continue` `pass` `else`)

**Comment by SL96-new** [comment]
```python
def tri_recursion(k):
  if(k > 0):
    result = k + tri_recursion(k - 1)
    print(result)
  else:
    result = 0
  return result

print("\n\nRecursion Example Results")
tri_recursion(6)
```

why the first printed result is 1 not 21 ?
![？](https://user-images.githubusercontent.com/85428512/159268522-ca9d3b87-bcb4-4aa1-b2af-4ab9eec10552.png)

**Comment by JKChai** [comment]
This is recursive function, and it will run till when `k == 0`, then run it back from `k == 1` back to `k == 6` by printing it back to the console.
